results_dir: "results/"
encode_metadata: "resources/metadata.tsv"
benchmark_set: "resources/benchmark_set.csv"

embedding_methods:
  - CCAIntegration
  - HarmonyIntegration
  - JointPCAIntegration
  - RPCAIntegration
  - FastMNNIntegration
  - none

distance_metrics:
  - euclidean
  - cosine

motif_dbs:
  - HOCOMOCOv11_HUMAN
  - JASPAR2020_vertebrates
  - CIS-BP
  - gimme.vertebrate.v5.0

tfsage_n: [1, 3, 7, 15, 23, 31]

test_sets:
  balanced:
    peak_width: 200
    blacklist_chroms: ["chrM", "chrY"]
    n_samples: 1000 # 500 positive, 500 negative
    p_positive: 0.5 # balanced
    random_state: 42

  moderate:
    peak_width: 200
    blacklist_chroms: ["chrM", "chrY"]
    n_samples: 2500 # 500 positive, 2000 negative
    p_positive: 0.2 # moderately imbalanced
    random_state: 42

  severe:
    peak_width: 200
    blacklist_chroms: ["chrM", "chrY"]
    n_samples: 10000 # 500 positive, 9500 negative
    p_positive: 0.05 # severely imbalanced
    random_state: 42
